### ISSUE TITLE
Lazy load models during import

### ISSUE THREAD

**Issue by BLKSerene** [VietHoang1710/khmer-nltk#5]
Hi, the NER and POS model are loaded automatically when importing `khmernltk`. Is it possible to load the model only when needed rather than during imports?

**Comment by VietHoang1512** [comment]
Theoretically, it's possible to implement an update in the code that would allow us to load the model weights only when necessary. However, it might lead to bugs in usage for those [dependents](https://github.com/VietHoang1512/khmer-nltk/network/dependents). Previously, we just left the model weights loaded automatically when importing for convenience and simplification (and also to align with tokenizers for many other languages).

**Comment by BLKSerene** [comment]
Users need to call `khmernltk.sentence_tokenize`, `khmernltk.word_tokenize`, and `khmernltk.pos_tag` in order to use the functionalities of `khmernltk`. So models could be loaded when these functions are invoked the first time rather then on `import khmernltk`. I don't see any breaking changes here.

If breaking changes do happen, bumping the major version to e.g. `2.0` should raise the awareness of users, I suppose.
